//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("xiao198_capstone2012Model", "FK__alarm_inf__binar__0DAF0CB0", "binary_file", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication2.Models.binary_file), "alarm_info", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.alarm_info), true)]
[assembly: EdmRelationshipAttribute("xiao198_capstone2012Model", "FK__user_anno__alarm__117F9D94", "alarm_info", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication2.Models.alarm_info), "user_annotation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.user_annotation), true)]
[assembly: EdmRelationshipAttribute("xiao198_capstone2012Model", "FK__user_anno__user___108B795B", "user_info", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication2.Models.user_info), "user_annotation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.user_annotation), true)]

#endregion

namespace MvcApplication2.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class xiao198_capstone2012Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new xiao198_capstone2012Entities object using the connection string found in the 'xiao198_capstone2012Entities' section of the application configuration file.
        /// </summary>
        public xiao198_capstone2012Entities() : base("name=xiao198_capstone2012Entities", "xiao198_capstone2012Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new xiao198_capstone2012Entities object.
        /// </summary>
        public xiao198_capstone2012Entities(string connectionString) : base(connectionString, "xiao198_capstone2012Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new xiao198_capstone2012Entities object.
        /// </summary>
        public xiao198_capstone2012Entities(EntityConnection connection) : base(connection, "xiao198_capstone2012Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<alarm_info> alarm_info
        {
            get
            {
                if ((_alarm_info == null))
                {
                    _alarm_info = base.CreateObjectSet<alarm_info>("alarm_info");
                }
                return _alarm_info;
            }
        }
        private ObjectSet<alarm_info> _alarm_info;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<binary_file> binary_file
        {
            get
            {
                if ((_binary_file == null))
                {
                    _binary_file = base.CreateObjectSet<binary_file>("binary_file");
                }
                return _binary_file;
            }
        }
        private ObjectSet<binary_file> _binary_file;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<score> scores
        {
            get
            {
                if ((_scores == null))
                {
                    _scores = base.CreateObjectSet<score>("scores");
                }
                return _scores;
            }
        }
        private ObjectSet<score> _scores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user_annotation> user_annotation
        {
            get
            {
                if ((_user_annotation == null))
                {
                    _user_annotation = base.CreateObjectSet<user_annotation>("user_annotation");
                }
                return _user_annotation;
            }
        }
        private ObjectSet<user_annotation> _user_annotation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user_info> user_info
        {
            get
            {
                if ((_user_info == null))
                {
                    _user_info = base.CreateObjectSet<user_info>("user_info");
                }
                return _user_info;
            }
        }
        private ObjectSet<user_info> _user_info;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the alarm_info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToalarm_info(alarm_info alarm_info)
        {
            base.AddObject("alarm_info", alarm_info);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the binary_file EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobinary_file(binary_file binary_file)
        {
            base.AddObject("binary_file", binary_file);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the scores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToscores(score score)
        {
            base.AddObject("scores", score);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user_annotation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser_annotation(user_annotation user_annotation)
        {
            base.AddObject("user_annotation", user_annotation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user_info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser_info(user_info user_info)
        {
            base.AddObject("user_info", user_info);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xiao198_capstone2012Model", Name="alarm_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class alarm_info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new alarm_info object.
        /// </summary>
        /// <param name="alarm_id">Initial value of the alarm_id property.</param>
        /// <param name="binary_file_id">Initial value of the binary_file_id property.</param>
        /// <param name="alarm_startime">Initial value of the alarm_startime property.</param>
        /// <param name="alarm_level">Initial value of the alarm_level property.</param>
        /// <param name="alarm_parcode">Initial value of the alarm_parcode property.</param>
        /// <param name="alarm_name">Initial value of the alarm_name property.</param>
        /// <param name="alarm_message">Initial value of the alarm_message property.</param>
        /// <param name="alarm_duration">Initial value of the alarm_duration property.</param>
        public static alarm_info Createalarm_info(global::System.String alarm_id, global::System.String binary_file_id, global::System.String alarm_startime, global::System.String alarm_level, global::System.String alarm_parcode, global::System.String alarm_name, global::System.String alarm_message, global::System.String alarm_duration)
        {
            alarm_info alarm_info = new alarm_info();
            alarm_info.alarm_id = alarm_id;
            alarm_info.binary_file_id = binary_file_id;
            alarm_info.alarm_startime = alarm_startime;
            alarm_info.alarm_level = alarm_level;
            alarm_info.alarm_parcode = alarm_parcode;
            alarm_info.alarm_name = alarm_name;
            alarm_info.alarm_message = alarm_message;
            alarm_info.alarm_duration = alarm_duration;
            return alarm_info;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alarm_id
        {
            get
            {
                return _alarm_id;
            }
            set
            {
                if (_alarm_id != value)
                {
                    Onalarm_idChanging(value);
                    ReportPropertyChanging("alarm_id");
                    _alarm_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("alarm_id");
                    Onalarm_idChanged();
                }
            }
        }
        private global::System.String _alarm_id;
        partial void Onalarm_idChanging(global::System.String value);
        partial void Onalarm_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String binary_file_id
        {
            get
            {
                return _binary_file_id;
            }
            set
            {
                Onbinary_file_idChanging(value);
                ReportPropertyChanging("binary_file_id");
                _binary_file_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("binary_file_id");
                Onbinary_file_idChanged();
            }
        }
        private global::System.String _binary_file_id;
        partial void Onbinary_file_idChanging(global::System.String value);
        partial void Onbinary_file_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alarm_startime
        {
            get
            {
                return _alarm_startime;
            }
            set
            {
                Onalarm_startimeChanging(value);
                ReportPropertyChanging("alarm_startime");
                _alarm_startime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alarm_startime");
                Onalarm_startimeChanged();
            }
        }
        private global::System.String _alarm_startime;
        partial void Onalarm_startimeChanging(global::System.String value);
        partial void Onalarm_startimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alarm_level
        {
            get
            {
                return _alarm_level;
            }
            set
            {
                Onalarm_levelChanging(value);
                ReportPropertyChanging("alarm_level");
                _alarm_level = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alarm_level");
                Onalarm_levelChanged();
            }
        }
        private global::System.String _alarm_level;
        partial void Onalarm_levelChanging(global::System.String value);
        partial void Onalarm_levelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alarm_parcode
        {
            get
            {
                return _alarm_parcode;
            }
            set
            {
                Onalarm_parcodeChanging(value);
                ReportPropertyChanging("alarm_parcode");
                _alarm_parcode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alarm_parcode");
                Onalarm_parcodeChanged();
            }
        }
        private global::System.String _alarm_parcode;
        partial void Onalarm_parcodeChanging(global::System.String value);
        partial void Onalarm_parcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alarm_name
        {
            get
            {
                return _alarm_name;
            }
            set
            {
                Onalarm_nameChanging(value);
                ReportPropertyChanging("alarm_name");
                _alarm_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alarm_name");
                Onalarm_nameChanged();
            }
        }
        private global::System.String _alarm_name;
        partial void Onalarm_nameChanging(global::System.String value);
        partial void Onalarm_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alarm_message
        {
            get
            {
                return _alarm_message;
            }
            set
            {
                Onalarm_messageChanging(value);
                ReportPropertyChanging("alarm_message");
                _alarm_message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alarm_message");
                Onalarm_messageChanged();
            }
        }
        private global::System.String _alarm_message;
        partial void Onalarm_messageChanging(global::System.String value);
        partial void Onalarm_messageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alarm_duration
        {
            get
            {
                return _alarm_duration;
            }
            set
            {
                Onalarm_durationChanging(value);
                ReportPropertyChanging("alarm_duration");
                _alarm_duration = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alarm_duration");
                Onalarm_durationChanged();
            }
        }
        private global::System.String _alarm_duration;
        partial void Onalarm_durationChanging(global::System.String value);
        partial void Onalarm_durationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_names
        {
            get
            {
                return _user_names;
            }
            set
            {
                Onuser_namesChanging(value);
                ReportPropertyChanging("user_names");
                _user_names = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_names");
                Onuser_namesChanged();
            }
        }
        private global::System.String _user_names;
        partial void Onuser_namesChanging(global::System.String value);
        partial void Onuser_namesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_predetermined
        {
            get
            {
                return _is_predetermined;
            }
            set
            {
                Onis_predeterminedChanging(value);
                ReportPropertyChanging("is_predetermined");
                _is_predetermined = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_predetermined");
                Onis_predeterminedChanged();
            }
        }
        private Nullable<global::System.Int32> _is_predetermined;
        partial void Onis_predeterminedChanging(Nullable<global::System.Int32> value);
        partial void Onis_predeterminedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String predetermined_result
        {
            get
            {
                return _predetermined_result;
            }
            set
            {
                Onpredetermined_resultChanging(value);
                ReportPropertyChanging("predetermined_result");
                _predetermined_result = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("predetermined_result");
                Onpredetermined_resultChanged();
            }
        }
        private global::System.String _predetermined_result;
        partial void Onpredetermined_resultChanging(global::System.String value);
        partial void Onpredetermined_resultChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xiao198_capstone2012Model", "FK__alarm_inf__binar__0DAF0CB0", "binary_file")]
        public binary_file binary_file
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<binary_file>("xiao198_capstone2012Model.FK__alarm_inf__binar__0DAF0CB0", "binary_file").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<binary_file>("xiao198_capstone2012Model.FK__alarm_inf__binar__0DAF0CB0", "binary_file").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<binary_file> binary_fileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<binary_file>("xiao198_capstone2012Model.FK__alarm_inf__binar__0DAF0CB0", "binary_file");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<binary_file>("xiao198_capstone2012Model.FK__alarm_inf__binar__0DAF0CB0", "binary_file", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xiao198_capstone2012Model", "FK__user_anno__alarm__117F9D94", "user_annotation")]
        public EntityCollection<user_annotation> user_annotation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_annotation>("xiao198_capstone2012Model.FK__user_anno__alarm__117F9D94", "user_annotation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_annotation>("xiao198_capstone2012Model.FK__user_anno__alarm__117F9D94", "user_annotation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xiao198_capstone2012Model", Name="binary_file")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class binary_file : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new binary_file object.
        /// </summary>
        /// <param name="binary_file_id">Initial value of the binary_file_id property.</param>
        /// <param name="binary_file_address">Initial value of the binary_file_address property.</param>
        /// <param name="binary_file_startime">Initial value of the binary_file_startime property.</param>
        public static binary_file Createbinary_file(global::System.String binary_file_id, global::System.String binary_file_address, global::System.DateTime binary_file_startime)
        {
            binary_file binary_file = new binary_file();
            binary_file.binary_file_id = binary_file_id;
            binary_file.binary_file_address = binary_file_address;
            binary_file.binary_file_startime = binary_file_startime;
            return binary_file;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String binary_file_id
        {
            get
            {
                return _binary_file_id;
            }
            set
            {
                if (_binary_file_id != value)
                {
                    Onbinary_file_idChanging(value);
                    ReportPropertyChanging("binary_file_id");
                    _binary_file_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("binary_file_id");
                    Onbinary_file_idChanged();
                }
            }
        }
        private global::System.String _binary_file_id;
        partial void Onbinary_file_idChanging(global::System.String value);
        partial void Onbinary_file_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String binary_file_address
        {
            get
            {
                return _binary_file_address;
            }
            set
            {
                Onbinary_file_addressChanging(value);
                ReportPropertyChanging("binary_file_address");
                _binary_file_address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("binary_file_address");
                Onbinary_file_addressChanged();
            }
        }
        private global::System.String _binary_file_address;
        partial void Onbinary_file_addressChanging(global::System.String value);
        partial void Onbinary_file_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime binary_file_startime
        {
            get
            {
                return _binary_file_startime;
            }
            set
            {
                Onbinary_file_startimeChanging(value);
                ReportPropertyChanging("binary_file_startime");
                _binary_file_startime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("binary_file_startime");
                Onbinary_file_startimeChanged();
            }
        }
        private global::System.DateTime _binary_file_startime;
        partial void Onbinary_file_startimeChanging(global::System.DateTime value);
        partial void Onbinary_file_startimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xiao198_capstone2012Model", "FK__alarm_inf__binar__0DAF0CB0", "alarm_info")]
        public EntityCollection<alarm_info> alarm_info
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<alarm_info>("xiao198_capstone2012Model.FK__alarm_inf__binar__0DAF0CB0", "alarm_info");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<alarm_info>("xiao198_capstone2012Model.FK__alarm_inf__binar__0DAF0CB0", "alarm_info", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xiao198_capstone2012Model", Name="score")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class score : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new score object.
        /// </summary>
        /// <param name="alarm_id">Initial value of the alarm_id property.</param>
        public static score Createscore(global::System.String alarm_id)
        {
            score score = new score();
            score.alarm_id = alarm_id;
            return score;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alarm_id
        {
            get
            {
                return _alarm_id;
            }
            set
            {
                if (_alarm_id != value)
                {
                    Onalarm_idChanging(value);
                    ReportPropertyChanging("alarm_id");
                    _alarm_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("alarm_id");
                    Onalarm_idChanged();
                }
            }
        }
        private global::System.String _alarm_id;
        partial void Onalarm_idChanging(global::System.String value);
        partial void Onalarm_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num_annotations
        {
            get
            {
                return _num_annotations;
            }
            set
            {
                Onnum_annotationsChanging(value);
                ReportPropertyChanging("num_annotations");
                _num_annotations = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_annotations");
                Onnum_annotationsChanged();
            }
        }
        private Nullable<global::System.Int32> _num_annotations;
        partial void Onnum_annotationsChanging(Nullable<global::System.Int32> value);
        partial void Onnum_annotationsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String annotation_ids
        {
            get
            {
                return _annotation_ids;
            }
            set
            {
                Onannotation_idsChanging(value);
                ReportPropertyChanging("annotation_ids");
                _annotation_ids = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("annotation_ids");
                Onannotation_idsChanged();
            }
        }
        private global::System.String _annotation_ids;
        partial void Onannotation_idsChanging(global::System.String value);
        partial void Onannotation_idsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ground_truth
        {
            get
            {
                return _ground_truth;
            }
            set
            {
                Onground_truthChanging(value);
                ReportPropertyChanging("ground_truth");
                _ground_truth = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ground_truth");
                Onground_truthChanged();
            }
        }
        private global::System.String _ground_truth;
        partial void Onground_truthChanging(global::System.String value);
        partial void Onground_truthChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xiao198_capstone2012Model", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xiao198_capstone2012Model", Name="user_annotation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_annotation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user_annotation object.
        /// </summary>
        /// <param name="annotation_id">Initial value of the annotation_id property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="alarm_id">Initial value of the alarm_id property.</param>
        public static user_annotation Createuser_annotation(global::System.String annotation_id, global::System.String user_id, global::System.String alarm_id)
        {
            user_annotation user_annotation = new user_annotation();
            user_annotation.annotation_id = annotation_id;
            user_annotation.user_id = user_id;
            user_annotation.alarm_id = alarm_id;
            return user_annotation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String annotation_id
        {
            get
            {
                return _annotation_id;
            }
            set
            {
                if (_annotation_id != value)
                {
                    Onannotation_idChanging(value);
                    ReportPropertyChanging("annotation_id");
                    _annotation_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("annotation_id");
                    Onannotation_idChanged();
                }
            }
        }
        private global::System.String _annotation_id;
        partial void Onannotation_idChanging(global::System.String value);
        partial void Onannotation_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.String _user_id;
        partial void Onuser_idChanging(global::System.String value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alarm_id
        {
            get
            {
                return _alarm_id;
            }
            set
            {
                Onalarm_idChanging(value);
                ReportPropertyChanging("alarm_id");
                _alarm_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alarm_id");
                Onalarm_idChanged();
            }
        }
        private global::System.String _alarm_id;
        partial void Onalarm_idChanging(global::System.String value);
        partial void Onalarm_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String annotation_result
        {
            get
            {
                return _annotation_result;
            }
            set
            {
                Onannotation_resultChanging(value);
                ReportPropertyChanging("annotation_result");
                _annotation_result = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("annotation_result");
                Onannotation_resultChanged();
            }
        }
        private global::System.String _annotation_result;
        partial void Onannotation_resultChanging(global::System.String value);
        partial void Onannotation_resultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> annotation_time
        {
            get
            {
                return _annotation_time;
            }
            set
            {
                Onannotation_timeChanging(value);
                ReportPropertyChanging("annotation_time");
                _annotation_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("annotation_time");
                Onannotation_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _annotation_time;
        partial void Onannotation_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onannotation_timeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xiao198_capstone2012Model", "FK__user_anno__alarm__117F9D94", "alarm_info")]
        public alarm_info alarm_info
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<alarm_info>("xiao198_capstone2012Model.FK__user_anno__alarm__117F9D94", "alarm_info").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<alarm_info>("xiao198_capstone2012Model.FK__user_anno__alarm__117F9D94", "alarm_info").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<alarm_info> alarm_infoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<alarm_info>("xiao198_capstone2012Model.FK__user_anno__alarm__117F9D94", "alarm_info");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<alarm_info>("xiao198_capstone2012Model.FK__user_anno__alarm__117F9D94", "alarm_info", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xiao198_capstone2012Model", "FK__user_anno__user___108B795B", "user_info")]
        public user_info user_info
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_info>("xiao198_capstone2012Model.FK__user_anno__user___108B795B", "user_info").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_info>("xiao198_capstone2012Model.FK__user_anno__user___108B795B", "user_info").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user_info> user_infoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_info>("xiao198_capstone2012Model.FK__user_anno__user___108B795B", "user_info");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user_info>("xiao198_capstone2012Model.FK__user_anno__user___108B795B", "user_info", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xiao198_capstone2012Model", Name="user_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user_info object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="user_name">Initial value of the user_name property.</param>
        /// <param name="user_password">Initial value of the user_password property.</param>
        /// <param name="user_firstname">Initial value of the user_firstname property.</param>
        /// <param name="user_lastname">Initial value of the user_lastname property.</param>
        public static user_info Createuser_info(global::System.String user_id, global::System.String user_name, global::System.String user_password, global::System.String user_firstname, global::System.String user_lastname)
        {
            user_info user_info = new user_info();
            user_info.user_id = user_id;
            user_info.user_name = user_name;
            user_info.user_password = user_password;
            user_info.user_firstname = user_firstname;
            user_info.user_lastname = user_lastname;
            return user_info;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.String _user_id;
        partial void Onuser_idChanging(global::System.String value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                Onuser_nameChanging(value);
                ReportPropertyChanging("user_name");
                _user_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_name");
                Onuser_nameChanged();
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_password
        {
            get
            {
                return _user_password;
            }
            set
            {
                Onuser_passwordChanging(value);
                ReportPropertyChanging("user_password");
                _user_password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_password");
                Onuser_passwordChanged();
            }
        }
        private global::System.String _user_password;
        partial void Onuser_passwordChanging(global::System.String value);
        partial void Onuser_passwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num_annotation
        {
            get
            {
                return _num_annotation;
            }
            set
            {
                Onnum_annotationChanging(value);
                ReportPropertyChanging("num_annotation");
                _num_annotation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_annotation");
                Onnum_annotationChanged();
            }
        }
        private Nullable<global::System.Int32> _num_annotation;
        partial void Onnum_annotationChanging(Nullable<global::System.Int32> value);
        partial void Onnum_annotationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> last_annotation_time
        {
            get
            {
                return _last_annotation_time;
            }
            set
            {
                Onlast_annotation_timeChanging(value);
                ReportPropertyChanging("last_annotation_time");
                _last_annotation_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_annotation_time");
                Onlast_annotation_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _last_annotation_time;
        partial void Onlast_annotation_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onlast_annotation_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_email
        {
            get
            {
                return _user_email;
            }
            set
            {
                Onuser_emailChanging(value);
                ReportPropertyChanging("user_email");
                _user_email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_email");
                Onuser_emailChanged();
            }
        }
        private global::System.String _user_email;
        partial void Onuser_emailChanging(global::System.String value);
        partial void Onuser_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_annotation_level
        {
            get
            {
                return _user_annotation_level;
            }
            set
            {
                Onuser_annotation_levelChanging(value);
                ReportPropertyChanging("user_annotation_level");
                _user_annotation_level = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_annotation_level");
                Onuser_annotation_levelChanged();
            }
        }
        private global::System.String _user_annotation_level;
        partial void Onuser_annotation_levelChanging(global::System.String value);
        partial void Onuser_annotation_levelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_firstname
        {
            get
            {
                return _user_firstname;
            }
            set
            {
                Onuser_firstnameChanging(value);
                ReportPropertyChanging("user_firstname");
                _user_firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_firstname");
                Onuser_firstnameChanged();
            }
        }
        private global::System.String _user_firstname;
        partial void Onuser_firstnameChanging(global::System.String value);
        partial void Onuser_firstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_lastname
        {
            get
            {
                return _user_lastname;
            }
            set
            {
                Onuser_lastnameChanging(value);
                ReportPropertyChanging("user_lastname");
                _user_lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_lastname");
                Onuser_lastnameChanged();
            }
        }
        private global::System.String _user_lastname;
        partial void Onuser_lastnameChanging(global::System.String value);
        partial void Onuser_lastnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xiao198_capstone2012Model", "FK__user_anno__user___108B795B", "user_annotation")]
        public EntityCollection<user_annotation> user_annotation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_annotation>("xiao198_capstone2012Model.FK__user_anno__user___108B795B", "user_annotation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_annotation>("xiao198_capstone2012Model.FK__user_anno__user___108B795B", "user_annotation", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
